spring:
  application:
    name: eureka-service
  cloud:
    discovery:
      client:
        health-indicator:
          enabled: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

server:
  port: 8761